name: Template Cleanup
on:
  push:
    branches: [ main, master ]
  workflow_dispatch: # Позволяет запускать вручную

permissions:
  contents: write # Явно даем права на запись

jobs:
  template-cleanup:
    if: github.repository != 'ObjReponse/web-content-processor-interview'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup template
        run: |
          # Получаем имя репозитория
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          
          echo "Cleaning up template for repository: ${GITHUB_REPOSITORY}"
          
          # Обновляем go.mod с правильным module path
          sed -i "s|github.com/ObjReponse/web-content-processor-interview|github.com/${GITHUB_REPOSITORY}|g" go.mod
          
          # Обновляем импорты в main.go
          sed -i "s|github.com/ObjReponse/web-content-processor-interview/processor|github.com/${GITHUB_REPOSITORY}/processor|g" main.go
          
          # Создаем файл-маркер что cleanup выполнен
          echo "Repository initialized from template on $(date)" > .template-initialized
          
          # Проверяем что есть изменения
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          # Коммитим изменения
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "🚀 Initialize repository from template
          
          - Updated module path to match repository
          - Updated imports in source files
          - Template cleanup completed"
          
          git push

      - name: Remove cleanup workflow
        run: |
          # Удаляем этот workflow после выполнения
          git rm .github/template-cleanup.yml
          git commit -m "🧹 Remove template cleanup workflow" || exit 0
          git push || exit 0